/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package voteandeat;

/**
 *
 * @author vipar
 */
public class Order extends javax.swing.JFrame {

    /**
     * Creates new form Order
     */
    public Order() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opjDialog1 = new javax.swing.JDialog();
        opd1gbbtn = new javax.swing.JButton();
        opd1cbtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        opjDialog2 = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        opd2okbtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        opccombox = new javax.swing.JComboBox<>();
        oprcombox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        opabtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        optbl = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        opsbtn = new javax.swing.JButton();
        opqtxtbox = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        oprbtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        hbtn = new javax.swing.JButton();
        vbtn = new javax.swing.JButton();
        oobtn = new javax.swing.JButton();
        obtn = new javax.swing.JButton();
        cbtn = new javax.swing.JButton();

        opjDialog1.setTitle("Confirmation");
        opjDialog1.setLocation(new java.awt.Point(540, 350));
        opjDialog1.setResizable(false);
        opjDialog1.setSize(new java.awt.Dimension(365, 205));

        opd1gbbtn.setText("Go back");
        opd1gbbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opd1gbbtnActionPerformed(evt);
            }
        });

        opd1cbtn.setText("Confirm");
        opd1cbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opd1cbtnActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Enter your password and click \"Confirm\" to confirm the order.");

        jPasswordField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout opjDialog1Layout = new javax.swing.GroupLayout(opjDialog1.getContentPane());
        opjDialog1.getContentPane().setLayout(opjDialog1Layout);
        opjDialog1Layout.setHorizontalGroup(
            opjDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opjDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(opjDialog1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, opjDialog1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(opd1gbbtn)
                .addGap(18, 18, 18)
                .addComponent(opd1cbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        opjDialog1Layout.setVerticalGroup(
            opjDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, opjDialog1Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(opjDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opd1gbbtn)
                    .addComponent(opd1cbtn))
                .addGap(36, 36, 36))
        );

        opjDialog2.setTitle("Order Placed !");
        opjDialog2.setLocation(new java.awt.Point(540, 350));
        opjDialog2.setPreferredSize(new java.awt.Dimension(365, 205));
        opjDialog2.setResizable(false);
        opjDialog2.setSize(new java.awt.Dimension(365, 205));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Thank you, Your order has been placed successfully!");

        opd2okbtn.setText("OK");
        opd2okbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opd2okbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout opjDialog2Layout = new javax.swing.GroupLayout(opjDialog2.getContentPane());
        opjDialog2.getContentPane().setLayout(opjDialog2Layout);
        opjDialog2Layout.setHorizontalGroup(
            opjDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, opjDialog2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, opjDialog2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(opd2okbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
        );
        opjDialog2Layout.setVerticalGroup(
            opjDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opjDialog2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(opd2okbtn)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 700));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(174, 234, 116), 5));
        jPanel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 72)); // NOI18N
        jLabel7.setText("PLACE YOUR ORDER");
        jLabel7.setToolTipText("");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 16, 775, 92));

        opccombox.setBackground(new java.awt.Color(174, 234, 116));
        opccombox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        opccombox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chicken and 3 Curries", "Fish and 3 Curries", "Egg and 3 Curries", "Vegetarian (4 Curries)" }));
        opccombox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(opccombox, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 248, -1));

        oprcombox.setBackground(new java.awt.Color(174, 234, 116));
        oprcombox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        oprcombox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "White Rice", "Red Rice" }));
        oprcombox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        oprcombox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                oprcomboxItemStateChanged(evt);
            }
        });
        jPanel2.add(oprcombox, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 195, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Select your choice and add it to the list :");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 683, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Qty:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, 50, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("+");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("x");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, -1, -1));

        opabtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        opabtn.setText("Add to list");
        opabtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(opabtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 220, 190, 63));

        optbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        optbl.setEnabled(false);
        optbl.setFillsViewportHeight(true);
        jScrollPane1.setViewportView(optbl);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 683, 200));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("<html><p>Double check your order <p>and click \"Submit\" to <p>confirm your Order<html>");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 530, 212, -1));

        opsbtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        opsbtn.setText("Submit");
        opsbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        opsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opsbtnActionPerformed(evt);
            }
        });
        jPanel2.add(opsbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 530, 188, 80));

        opqtxtbox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel2.add(opqtxtbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 180, 100, -1));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        oprbtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        oprbtn.setText("Remove");
        oprbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("<html> Enter the order code and click<p>\"Remove\" to remove a record");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(oprbtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oprbtn))
                .addContainerGap())
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, 260, 140));

        hbtn.setBackground(new java.awt.Color(0, 102, 0));
        hbtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        hbtn.setText("Home");
        hbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hbtnActionPerformed(evt);
            }
        });

        vbtn.setBackground(new java.awt.Color(0, 102, 0));
        vbtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        vbtn.setText("Vote");
        vbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vbtnActionPerformed(evt);
            }
        });

        oobtn.setBackground(new java.awt.Color(0, 102, 0));
        oobtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        oobtn.setText("<html><p align = center>Other</p><p>Orders</p>");
        oobtn.setActionCommand("<html><p>Other</p><p>Orders</p>");
        oobtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        oobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oobtnActionPerformed(evt);
            }
        });

        obtn.setBackground(new java.awt.Color(174, 234, 116));
        obtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        obtn.setForeground(new java.awt.Color(255, 255, 255));
        obtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/voteandeat/Images/order-64.png"))); // NOI18N
        obtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        obtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/voteandeat/Images/r-arrow-64.png"))); // NOI18N

        cbtn.setBackground(new java.awt.Color(204, 0, 0));
        cbtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cbtn.setText("Cancel");
        cbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(vbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(oobtn, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(obtn, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(cbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 861, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(hbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(vbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(obtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(oobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void oprcomboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_oprcomboxItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_oprcomboxItemStateChanged

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void hbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hbtnActionPerformed
        // TODO add your handling code here:
        dispose();
        new Home().setVisible(true);
    }//GEN-LAST:event_hbtnActionPerformed

    private void vbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vbtnActionPerformed
        // TODO add your handling code here:
        dispose();
        new Vote().setVisible(true);
    }//GEN-LAST:event_vbtnActionPerformed

    private void oobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oobtnActionPerformed
        // TODO add your handling code here:
        dispose();
        new OtherOrders().setVisible(true);
    }//GEN-LAST:event_oobtnActionPerformed

    private void cbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtnActionPerformed
        // TODO add your handling code here:
        dispose();
        new WelcomePage().setVisible(true);
    }//GEN-LAST:event_cbtnActionPerformed

    private void opd1cbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opd1cbtnActionPerformed
        // TODO add your handling code here:
        opjDialog1.dispose();
        opjDialog2.setVisible(true);
    }//GEN-LAST:event_opd1cbtnActionPerformed

    private void opd2okbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opd2okbtnActionPerformed
        // TODO add your handling code here:
        dispose();
        opjDialog2.dispose();
        new Home().setVisible(true);
    }//GEN-LAST:event_opd2okbtnActionPerformed

    private void opd1gbbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opd1gbbtnActionPerformed
        // TODO add your handling code here:
        opjDialog1.dispose();
    }//GEN-LAST:event_opd1gbbtnActionPerformed

    private void opsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opsbtnActionPerformed
        // TODO add your handling code here:
        opjDialog1.setVisible(true);
    }//GEN-LAST:event_opsbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cbtn;
    private javax.swing.JButton hbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton obtn;
    private javax.swing.JButton oobtn;
    private javax.swing.JButton opabtn;
    private javax.swing.JComboBox<String> opccombox;
    private javax.swing.JButton opd1cbtn;
    private javax.swing.JButton opd1gbbtn;
    private javax.swing.JButton opd2okbtn;
    private javax.swing.JDialog opjDialog1;
    private javax.swing.JDialog opjDialog2;
    private javax.swing.JTextField opqtxtbox;
    private javax.swing.JButton oprbtn;
    private javax.swing.JComboBox<String> oprcombox;
    private javax.swing.JButton opsbtn;
    private javax.swing.JTable optbl;
    private javax.swing.JButton vbtn;
    // End of variables declaration//GEN-END:variables
}
