/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package voteandeat;

/**
 *
 * @author vipar
 */
public class OtherOrders extends javax.swing.JFrame {

    /**
     * Creates new form OtherOrders
     */
    public OtherOrders() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        oopjDialog1 = new javax.swing.JDialog();
        opd1gbbtn = new javax.swing.JButton();
        opd1cbtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        oopjDialog2 = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        opd2okbtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        oopcb1 = new javax.swing.JCheckBox();
        oopcb2 = new javax.swing.JCheckBox();
        oopcb3 = new javax.swing.JCheckBox();
        oopsbtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        oopqtxtbox3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        oopqtxtbox2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        oopqtxtbox1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        oopdtxtbox = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        hbtn = new javax.swing.JButton();
        vbtn = new javax.swing.JButton();
        obtn = new javax.swing.JButton();
        oobtn = new javax.swing.JButton();
        cbtn = new javax.swing.JButton();

        oopjDialog1.setTitle("Confirmation");
        oopjDialog1.setLocation(new java.awt.Point(540, 350));
        oopjDialog1.setResizable(false);
        oopjDialog1.setSize(new java.awt.Dimension(365, 205));

        opd1gbbtn.setText("Go back");
        opd1gbbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opd1gbbtnActionPerformed(evt);
            }
        });

        opd1cbtn.setText("Confirm");
        opd1cbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opd1cbtnActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Enter your password and click \"Confirm\" to confirm the order.");

        jPasswordField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout oopjDialog1Layout = new javax.swing.GroupLayout(oopjDialog1.getContentPane());
        oopjDialog1.getContentPane().setLayout(oopjDialog1Layout);
        oopjDialog1Layout.setHorizontalGroup(
            oopjDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oopjDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(oopjDialog1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, oopjDialog1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(opd1gbbtn)
                .addGap(18, 18, 18)
                .addComponent(opd1cbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        oopjDialog1Layout.setVerticalGroup(
            oopjDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, oopjDialog1Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(oopjDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opd1gbbtn)
                    .addComponent(opd1cbtn))
                .addGap(36, 36, 36))
        );

        oopjDialog2.setTitle("Order Placed !");
        oopjDialog2.setLocation(new java.awt.Point(540, 350));
        oopjDialog2.setPreferredSize(new java.awt.Dimension(365, 205));
        oopjDialog2.setResizable(false);
        oopjDialog2.setSize(new java.awt.Dimension(365, 205));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Thank you, Your order has been placed successfully!");

        opd2okbtn.setText("OK");
        opd2okbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opd2okbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout oopjDialog2Layout = new javax.swing.GroupLayout(oopjDialog2.getContentPane());
        oopjDialog2.getContentPane().setLayout(oopjDialog2Layout);
        oopjDialog2Layout.setHorizontalGroup(
            oopjDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, oopjDialog2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, oopjDialog2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(opd2okbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
        );
        oopjDialog2Layout.setVerticalGroup(
            oopjDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oopjDialog2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(opd2okbtn)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 700));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(174, 234, 116), 5));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 72)); // NOI18N
        jLabel7.setText("PLACE YOUR ORDER");
        jLabel7.setToolTipText("");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 16, 790, 92));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Select your choice and add it to the list :");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 158, 683, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/voteandeat/Images/Chocolate Cake.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 225, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 201, -1, -1));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/voteandeat/Images/StrawberryButtercream.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 201, 200, -1));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/voteandeat/Images/ChocolateCakeCaramelFrosting.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(586, 201, 200, -1));

        oopcb1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        oopcb1.setText("<html><p>Chocolate<p>Icing<p>Cake");
        oopcb1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        oopcb1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        oopcb1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        oopcb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oopcb1ActionPerformed(evt);
            }
        });
        jPanel2.add(oopcb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 455, 208, -1));

        oopcb2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        oopcb2.setText("<html><p>Strawberry<p>Buttercream<p>Cake");
        oopcb2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        oopcb2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        oopcb2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel2.add(oopcb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 455, 200, -1));

        oopcb3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        oopcb3.setText("<html><p>Chocolate<p>Caramel<p>Cake");
        oopcb3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        oopcb3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        oopcb3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel2.add(oopcb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(586, 455, 200, -1));

        oopsbtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        oopsbtn.setText("Submit");
        oopsbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        oopsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oopsbtnActionPerformed(evt);
            }
        });
        jPanel2.add(oopsbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 580, 202, 86));

        oopqtxtbox3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Quantity:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(oopqtxtbox3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(oopqtxtbox3, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 540, 190, 30));

        oopqtxtbox2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Quantity:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(oopqtxtbox2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(oopqtxtbox2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addComponent(jLabel6))
        );

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 540, -1, -1));

        jPanel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        oopqtxtbox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Quantity:");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(oopqtxtbox1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(oopqtxtbox1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addComponent(jLabel8))
        );

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 540, -1, -1));

        oopdtxtbox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        oopdtxtbox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(oopdtxtbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 610, 150, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Order required data (format: dd/mm/yyyy):");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 620, -1, -1));

        hbtn.setBackground(new java.awt.Color(0, 102, 0));
        hbtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        hbtn.setText("Home");
        hbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hbtnActionPerformed(evt);
            }
        });

        vbtn.setBackground(new java.awt.Color(0, 102, 0));
        vbtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        vbtn.setText("Vote");
        vbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vbtnActionPerformed(evt);
            }
        });

        obtn.setBackground(new java.awt.Color(0, 102, 0));
        obtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        obtn.setText("Order");
        obtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        obtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obtnActionPerformed(evt);
            }
        });

        oobtn.setBackground(new java.awt.Color(174, 234, 116));
        oobtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        oobtn.setForeground(new java.awt.Color(255, 255, 255));
        oobtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/voteandeat/Images/cake-64.png"))); // NOI18N
        oobtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        oobtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/voteandeat/Images/r-arrow-64.png"))); // NOI18N

        cbtn.setBackground(new java.awt.Color(204, 0, 0));
        cbtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cbtn.setText("Cancel");
        cbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(vbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(obtn, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(oobtn, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(cbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 861, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(hbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(vbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(obtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(oobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void oopcb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oopcb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oopcb1ActionPerformed

    private void hbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hbtnActionPerformed
        // TODO add your handling code here:
        dispose();
        new Home().setVisible(true);
    }//GEN-LAST:event_hbtnActionPerformed

    private void vbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vbtnActionPerformed
        // TODO add your handling code here:
        dispose();
        new Vote().setVisible(true);
    }//GEN-LAST:event_vbtnActionPerformed

    private void obtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obtnActionPerformed
        // TODO add your handling code here:
        dispose();
        new Order().setVisible(true);
    }//GEN-LAST:event_obtnActionPerformed

    private void cbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtnActionPerformed
        // TODO add your handling code here:
        dispose();
        new WelcomePage().setVisible(true);
    }//GEN-LAST:event_cbtnActionPerformed

    private void opd1gbbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opd1gbbtnActionPerformed
        // TODO add your handling code here:
        oopjDialog1.dispose();
    }//GEN-LAST:event_opd1gbbtnActionPerformed

    private void opd1cbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opd1cbtnActionPerformed
        // TODO add your handling code here:
        oopjDialog1.dispose();
        oopjDialog2.setVisible(true);
    }//GEN-LAST:event_opd1cbtnActionPerformed

    private void opd2okbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opd2okbtnActionPerformed
        // TODO add your handling code here:
        dispose();
        oopjDialog2.dispose();
        new Home().setVisible(true);
    }//GEN-LAST:event_opd2okbtnActionPerformed

    private void oopsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oopsbtnActionPerformed
        // TODO add your handling code here:
        oopjDialog1.setVisible(true);
    }//GEN-LAST:event_oopsbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OtherOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OtherOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OtherOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OtherOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OtherOrders().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cbtn;
    private javax.swing.JButton hbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JButton obtn;
    private javax.swing.JButton oobtn;
    private javax.swing.JCheckBox oopcb1;
    private javax.swing.JCheckBox oopcb2;
    private javax.swing.JCheckBox oopcb3;
    private javax.swing.JTextField oopdtxtbox;
    private javax.swing.JDialog oopjDialog1;
    private javax.swing.JDialog oopjDialog2;
    private javax.swing.JTextField oopqtxtbox1;
    private javax.swing.JTextField oopqtxtbox2;
    private javax.swing.JTextField oopqtxtbox3;
    private javax.swing.JButton oopsbtn;
    private javax.swing.JButton opd1cbtn;
    private javax.swing.JButton opd1gbbtn;
    private javax.swing.JButton opd2okbtn;
    private javax.swing.JButton vbtn;
    // End of variables declaration//GEN-END:variables
}
