/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package canteentest01;

import java.awt.Color;

/**
 *
 * @author Shadow
 */
public class MealProcessing01 extends javax.swing.JFrame {

    /**
     * Creates new form MealProcessing01
     */
    
    private int i,j;
    private String[] date = new String[2];
    private String[][] curry = new String[3][3]; 
    private int [][] meat = new int[3][3];
    private String[][] meatName = new String[3][3];
    private int[] comf={1,1,1};
    private int canteen=2;
    private int[] mcomf={0,0,0};
    
    public MealProcessing01() {
        initComponents();
        getContentPane().setBackground(Color.decode("#aaccff"));
        //this.canteen = t1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jToolBar2 = new javax.swing.JToolBar();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        mpmf1 = new javax.swing.JCheckBox();
        mpmf2 = new javax.swing.JCheckBox();
        mpmf3 = new javax.swing.JCheckBox();
        mpmc1 = new javax.swing.JCheckBox();
        mpmc2 = new javax.swing.JCheckBox();
        mpmc3 = new javax.swing.JCheckBox();
        mpme1 = new javax.swing.JCheckBox();
        mpme2 = new javax.swing.JCheckBox();
        jToolBar1 = new javax.swing.JToolBar();
        jPanel2 = new javax.swing.JPanel();
        curry11 = new javax.swing.JLabel();
        curry12 = new javax.swing.JLabel();
        curry13 = new javax.swing.JLabel();
        mpc11 = new javax.swing.JTextField();
        mpc12 = new javax.swing.JTextField();
        mpc13 = new javax.swing.JTextField();
        jToolBar3 = new javax.swing.JToolBar();
        jPanel3 = new javax.swing.JPanel();
        curry21 = new javax.swing.JLabel();
        curry22 = new javax.swing.JLabel();
        curry23 = new javax.swing.JLabel();
        mpc21 = new javax.swing.JTextField();
        mpc22 = new javax.swing.JTextField();
        mpc23 = new javax.swing.JTextField();
        jToolBar4 = new javax.swing.JToolBar();
        jPanel4 = new javax.swing.JPanel();
        curry31 = new javax.swing.JLabel();
        curry32 = new javax.swing.JLabel();
        curry33 = new javax.swing.JLabel();
        mpc31 = new javax.swing.JTextField();
        mpc32 = new javax.swing.JTextField();
        mpc33 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        mprdate = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        mpmdate = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        warnning = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        jTabbedPane2.setBackground(new java.awt.Color(204, 255, 255));
        jTabbedPane2.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jToolBar2.setRollover(true);
        jToolBar2.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Fish");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Chicken");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Egg");

        mpmf1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        mpmf1.setText("Fish 1");

        mpmf2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        mpmf2.setText("Fish 2");

        mpmf3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        mpmf3.setText("Fish3");

        mpmc1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        mpmc1.setText("Curry 1 Chicken");

        mpmc2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        mpmc2.setText("Curry 2 Chicken");

        mpmc3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        mpmc3.setText("Curry 3 Chicken");

        mpme1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        mpme1.setText("Boilded Egg");

        mpme2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        mpme2.setText("Boilded Egg 2");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mpmc1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(mpmf1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mpmf2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mpmf3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(mpmc2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mpmc3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mpme1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mpme2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(356, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mpmf1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mpmf2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mpmf3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mpmc1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mpmc2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mpmc3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mpme1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mpme2)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jToolBar2.add(jPanel6);

        jTabbedPane2.addTab("Meats", jToolBar2);

        jToolBar1.setRollover(true);

        curry11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        curry11.setText("Curry set 1 option 1");

        curry12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        curry12.setText("Curry set 1 option 2");

        curry13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        curry13.setText("Curry set 1 option 3");

        mpc11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        mpc11.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        mpc12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        mpc12.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        mpc13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        mpc13.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(curry12, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(curry13, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(curry11, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mpc11, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mpc12, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mpc13, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(curry11)
                    .addComponent(mpc11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(curry12)
                    .addComponent(mpc12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(curry13)
                    .addComponent(mpc13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(209, Short.MAX_VALUE))
        );

        jToolBar1.add(jPanel2);

        jTabbedPane2.addTab("Curry set 01", jToolBar1);

        jToolBar3.setRollover(true);

        curry21.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        curry21.setText("Curry set 2 option 1");

        curry22.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        curry22.setText("Curry set 2 option 2");

        curry23.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        curry23.setText("Curry set 2 option 3");

        mpc21.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        mpc21.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        mpc22.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        mpc22.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        mpc23.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        mpc23.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(curry22, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(curry23, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(curry21, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mpc21, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mpc22, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mpc23, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(curry21)
                    .addComponent(mpc21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(curry22)
                    .addComponent(mpc22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(curry23)
                    .addComponent(mpc23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(211, Short.MAX_VALUE))
        );

        jToolBar3.add(jPanel3);

        jTabbedPane2.addTab("Curry set 02", jToolBar3);

        jToolBar4.setRollover(true);

        curry31.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        curry31.setText("Curry set 3 option 1");

        curry32.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        curry32.setText("Curry set 3 option 2");

        curry33.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        curry33.setText("Curry set 3 option 3");

        mpc31.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        mpc31.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        mpc32.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        mpc32.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        mpc33.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        mpc33.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(curry32, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(curry33, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(curry31, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mpc31, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mpc32, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mpc33, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(curry31)
                    .addComponent(mpc31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(curry32)
                    .addComponent(mpc32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(curry33)
                    .addComponent(mpc33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(211, Short.MAX_VALUE))
        );

        jToolBar4.add(jPanel4);

        jTabbedPane2.addTab("Curry set 03", jToolBar4);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton2.setText("Log Out");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton3.setText("Orders");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton4.setText("VotingCount");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton5.setText("Main Menu");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        mprdate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        mprdate.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("(Date Format)");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("(yyyymmdd)");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("(Ex- 20201201)");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Meal Process");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Menu Date");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Review Date");

        mpmdate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        mpmdate.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Date Allocations");

        warnning.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        warnning.setForeground(new java.awt.Color(255, 0, 0));
        warnning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton6.setText("New Process");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(278, 278, 278)
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mprdate, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mpmdate, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 17, Short.MAX_VALUE))))
            .addComponent(warnning, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(warnning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mprdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mpmdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jButton3)
                        .addComponent(jButton4)
                        .addComponent(jButton5))
                    .addComponent(jButton6))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new VotingCount01().setVisible(true); 
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new Order01().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new AdminMainMenu(canteen).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new Loginpage01().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        getDate();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MealProcessing01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MealProcessing01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MealProcessing01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MealProcessing01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MealProcessing01().setVisible(true);
            }
        });
    }
    
    /*private void getDate(){
        date[0]=mprdate.getText();
    }*/
    
    private void getCurry(){
        int[] t1={0,0,0};
        
        curry[0][0]=mpc11.getText();
        curry[0][1]=mpc12.getText();
        curry[0][2]=mpc13.getText();
        
        curry[1][0]=mpc21.getText();
        curry[1][1]=mpc22.getText();
        curry[1][2]=mpc23.getText();
        
        curry[2][0]=mpc31.getText();
        curry[2][1]=mpc32.getText();
        curry[2][2]=mpc33.getText();
        
        for(i=0;i<3;++i){
            for(j=0;j<3;++j){
                if(curry[i][j].isEmpty()==true){
                    ++t1[i];
                }
            }
        }
        
        if(t1[0]>1){
            warnning.setText("*  please input at least two options for curry set 01  *");
        }
        else{
            if(t1[1]>1){
                warnning.setText("*  please input at least two options for curry set 02  *");
            }
            else{
                if(t1[2]>1){
                    warnning.setText("*  please input at least two options for curry set 03  *");
                }
                else{
                    comf[2]=0;
                    insertToVoting();
                }
            }
        }
    }
    
    private void getMeat(){
        int[] t1={0,0,0};
        for(i=0;i<3;++i){
            for(j=0;j<3;++j){
                meat[i][j]=0;
            }
        }
        
        if(mpmf1.isSelected()==true){
            meat[0][0]=1;
            meatName[0][0]="Fish 1";
        }
        if(mpmf2.isSelected()==true){
            meat[0][1]=1;
            meatName[0][1]="Fish 2";
        }
        if(mpmf3.isSelected()==true){
            meat[0][2]=1;
            meatName[0][2]="Fish 3";
        }
        
        if(mpmc1.isSelected()==true){
            meat[1][0]=1;
            meatName[1][0]="Chicken 1";
        }
        if(mpmc2.isSelected()==true){
            meat[1][1]=1;
            meatName[1][1]="Chicken 2";
        }
        if(mpmc3.isSelected()==true){
            meat[1][2]=1;
            meatName[1][2]="Chicken 3";
        }
        
        if(mpme1.isSelected()==true){
            meat[2][0]=1;
            meatName[2][0]="Egg 1";
        }
        if(mpme2.isSelected()==true){
            meat[2][1]=1;
            meatName[2][1]="Egg 2";
        }
        
        for(i=0;i<3;++i){
            for(j=0;j<3;++j){
                if(meat[i][j]==0){
                    ++t1[i];
                }
            }
        }
        
        if(t1[0]>2 && mcomf[0]==0){
            warnning.setText("*  you have not selected a Fish type !!! click 'submit' to continue  *");
            mcomf[0]=1;
        }
        else{
            if(t1[1]>2 && mcomf[1]==0){
                warnning.setText("*  you have not selected a Chicken type !!! click 'submit' to continue  *");
                mcomf[1]=1;
            }
            else{
                if(t1[2]>1 && mcomf[2]==0){
                    warnning.setText("*  you have not selected a Egg type !!! click 'submit' to continue  *");
                    mcomf[2]=1;
                }
                else{
                    comf[1]=0;
                    getCurry();
                }
            }
        }
        
    }
    
    private void getDate(){
        int[] t1=new int[2];
        int[] t2=new int[2];
        int v1=0;
        int v2=0;
        warnning.setText(null);
        Calculations f1=new Calculations(mprdate.getText());
        Calculations f2=new Calculations(mpmdate.getText());
        t1=f1.checkDate();
        t2=f2.checkDate();
        
        if(t1[0]==3){
            warnning.setText("*  Enter a Review Date  *");
        }
        else{
            if(t2[0]==3){
                warnning.setText("*  Enter a Menu Date  *");
            }
            else{
                if(v1==0){
                    warnning.setText(null);
                    if(t1[0]==0){
                        if(t1[1]==0){
                            warnning.setText("* Invalid Review Date *");
                        }
                        else{
                            if(t1[1]==1){
                               warnning.setText("* Invalid Review Date - Incorrect Date *"); 
                            }
                            else{
                                if(t1[1]==2){
                                    warnning.setText("* Invalid Review Date - Incorrect Month *");
                                }
                                else{
                                    if(t1[1]==3){
                                        warnning.setText("* Invalid Review Date - Incorrect Year *");
                                    }
                                }
                            }
                        }
                    }
                    else{
                        warnning.setText(null);
                        if(t2[0]==0){
                            if(t2[1]==0){
                                warnning.setText("* Invalid Menu Date *");
                            }
                            else{
                                if(t2[1]==1){
                                   warnning.setText("* Invalid Menu Date - Incorrect Date *"); 
                                }
                                else{
                                    if(t2[1]==2){
                                        warnning.setText("* Invalid Menu Date - Incorrect Month *");
                                    }
                                    else{
                                        if(t2[1]==3){
                                            warnning.setText("* Invalid Menu Date - Incorrect Year *");
                                        }
                                    }
                                }
                            }
                        }
                        else{
                            date[0]= mprdate.getText();
                            date[1] = mpmdate.getText();
                            comf[0]=0;
                            getMeat();
                        }
                    }
                }
            }
        }
    }
    
    private void insertToVoting(){
        if(comf[0]==1){
            warnning.setText("*  Something went wrong !!! check input dates  *");
        }
        else{
            if(comf[1]==1){
                warnning.setText("*  Something went wrong !!! check input meat types  *");
            }
            else{
                if(comf[2]==1){
                    warnning.setText("*  Something went wrong !!! check input curry sets  *");
                }
                else{
                    SQLClass s1 = new SQLClass();
                    int tmp=s1.setVoting(canteen,date,meatName,curry);
                    switch (tmp){
                        case 0:
                            warnning.setText("Something went wrong !!! Unsuccessful Query");
                            break;
                        case 1:
                            warnning.setText("# voting for menu date :"+date[1]+" is set #");
                            break;
                    }
                    for(i=0;i<3;++i){
                        comf[i]=1;
                        mcomf[i]=0;
                    }
                }
            }
        }
        
    }
    private void clear(){
        
        mpmf1.setSelected(false);
        mpmf2.setSelected(false);
        mpmf3.setSelected(false);
        
        mpmc1.setSelected(false);
        mpmc2.setSelected(false);
        mpmc3.setSelected(false);
        
        mpme1.setSelected(false);
        mpme2.setSelected(false);
        
        mpc11.setText(null);
        mpc12.setText(null);
        mpc13.setText(null);
        
        mpc21.setText(null);
        mpc22.setText(null);
        mpc23.setText(null);
        
        mpc31.setText(null);
        mpc32.setText(null);
        mpc33.setText(null);
        
        mprdate.setText(null);
        mpmdate.setText(null);
    
        for(i=0;i<3;++i){
            for(j=0;j<3;++j){
                curry[i][j]=null;
                meat[i][j]=0;
            }
        }
        date[0]=null;
        date[1]=null;
        
        warnning.setText(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel curry11;
    private javax.swing.JLabel curry12;
    private javax.swing.JLabel curry13;
    private javax.swing.JLabel curry21;
    private javax.swing.JLabel curry22;
    private javax.swing.JLabel curry23;
    private javax.swing.JLabel curry31;
    private javax.swing.JLabel curry32;
    private javax.swing.JLabel curry33;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JToolBar jToolBar4;
    private javax.swing.JTextField mpc11;
    private javax.swing.JTextField mpc12;
    private javax.swing.JTextField mpc13;
    private javax.swing.JTextField mpc21;
    private javax.swing.JTextField mpc22;
    private javax.swing.JTextField mpc23;
    private javax.swing.JTextField mpc31;
    private javax.swing.JTextField mpc32;
    private javax.swing.JTextField mpc33;
    private javax.swing.JCheckBox mpmc1;
    private javax.swing.JCheckBox mpmc2;
    private javax.swing.JCheckBox mpmc3;
    private javax.swing.JTextField mpmdate;
    private javax.swing.JCheckBox mpme1;
    private javax.swing.JCheckBox mpme2;
    private javax.swing.JCheckBox mpmf1;
    private javax.swing.JCheckBox mpmf2;
    private javax.swing.JCheckBox mpmf3;
    private javax.swing.JTextField mprdate;
    private javax.swing.JLabel warnning;
    // End of variables declaration//GEN-END:variables
}
