/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package canteentest01;

/**
 *
 * @author Shadow
 */
public class VotingCount01 extends javax.swing.JFrame {

    /**
     * Creates new form OrderCount01
     */
    
    private int i,j;
    
    private int[][] count = new int[6][3];
    private double[][] value = new double[6][3];
    private String[][] cnames = new String[3][3];
    private String menuDate=null;
    private int[] menu = new int[6];
    private int canteen=2;
    
    public VotingCount01() {
        initComponents();
        //this.canteen=t1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jToolBar2 = new javax.swing.JToolBar();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fish1 = new javax.swing.JLabel();
        fish1n = new javax.swing.JLabel();
        fish1p = new javax.swing.JProgressBar();
        fish2 = new javax.swing.JLabel();
        fish2n = new javax.swing.JLabel();
        fish2p = new javax.swing.JProgressBar();
        jLabel6 = new javax.swing.JLabel();
        chicken1 = new javax.swing.JLabel();
        chicken1n = new javax.swing.JLabel();
        chicken1p = new javax.swing.JProgressBar();
        fish3 = new javax.swing.JLabel();
        fish3n = new javax.swing.JLabel();
        fish3p = new javax.swing.JProgressBar();
        chicken2 = new javax.swing.JLabel();
        chicken2n = new javax.swing.JLabel();
        chicken2p = new javax.swing.JProgressBar();
        chicken3 = new javax.swing.JLabel();
        chicken3p = new javax.swing.JProgressBar();
        chicken3n = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        egg1 = new javax.swing.JLabel();
        egg1n = new javax.swing.JLabel();
        egg1p = new javax.swing.JProgressBar();
        egg2 = new javax.swing.JLabel();
        egg2n = new javax.swing.JLabel();
        egg2p = new javax.swing.JProgressBar();
        jLabel8 = new javax.swing.JLabel();
        f1 = new javax.swing.JCheckBox();
        f2 = new javax.swing.JCheckBox();
        f3 = new javax.swing.JCheckBox();
        c1 = new javax.swing.JCheckBox();
        c2 = new javax.swing.JCheckBox();
        c3 = new javax.swing.JCheckBox();
        e1 = new javax.swing.JCheckBox();
        e2 = new javax.swing.JCheckBox();
        jToolBar1 = new javax.swing.JToolBar();
        jPanel2 = new javax.swing.JPanel();
        curry11 = new javax.swing.JLabel();
        curry12 = new javax.swing.JLabel();
        curry13 = new javax.swing.JLabel();
        curry11n = new javax.swing.JLabel();
        curry12n = new javax.swing.JLabel();
        curry13n = new javax.swing.JLabel();
        curry11p = new javax.swing.JProgressBar();
        curry12p = new javax.swing.JProgressBar();
        curry13p = new javax.swing.JProgressBar();
        jLabel7 = new javax.swing.JLabel();
        c11 = new javax.swing.JCheckBox();
        c12 = new javax.swing.JCheckBox();
        c13 = new javax.swing.JCheckBox();
        jToolBar3 = new javax.swing.JToolBar();
        jPanel3 = new javax.swing.JPanel();
        curry21 = new javax.swing.JLabel();
        curry22 = new javax.swing.JLabel();
        curry23 = new javax.swing.JLabel();
        curry21n = new javax.swing.JLabel();
        curry22n = new javax.swing.JLabel();
        curry23n = new javax.swing.JLabel();
        curry21p = new javax.swing.JProgressBar();
        curry22p = new javax.swing.JProgressBar();
        curry23p = new javax.swing.JProgressBar();
        jLabel5 = new javax.swing.JLabel();
        c21 = new javax.swing.JCheckBox();
        c22 = new javax.swing.JCheckBox();
        c23 = new javax.swing.JCheckBox();
        jToolBar4 = new javax.swing.JToolBar();
        jPanel4 = new javax.swing.JPanel();
        curry31 = new javax.swing.JLabel();
        curry32 = new javax.swing.JLabel();
        curry33 = new javax.swing.JLabel();
        curry31n = new javax.swing.JLabel();
        curry32n = new javax.swing.JLabel();
        curry33n = new javax.swing.JLabel();
        curry31p = new javax.swing.JProgressBar();
        curry32p = new javax.swing.JProgressBar();
        curry33p = new javax.swing.JProgressBar();
        jLabel4 = new javax.swing.JLabel();
        c31 = new javax.swing.JCheckBox();
        c32 = new javax.swing.JCheckBox();
        c33 = new javax.swing.JCheckBox();
        jToolBar5 = new javax.swing.JToolBar();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        vegtxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        vcmdate = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        warring = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        jMenu2.setText("File");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar1.add(jMenu3);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);

        jTabbedPane2.setBackground(new java.awt.Color(204, 255, 255));
        jTabbedPane2.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jToolBar2.setRollover(true);
        jToolBar2.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Fish");

        fish1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        fish1.setText("Oiled Fish");

        fish1n.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        fish1n.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fish1n.setText("0");

        fish2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        fish2.setText("Curry Fish");

        fish2n.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        fish2n.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fish2n.setText("0");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Chicken");

        chicken1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        chicken1.setText("Curry 1 Chicken");

        chicken1n.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        chicken1n.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        chicken1n.setText("0");

        fish3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        fish3.setText("Curry 2 Fish");

        fish3n.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        fish3n.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fish3n.setText("0");

        chicken2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        chicken2.setText("Curry 2 Chicken");

        chicken2n.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        chicken2n.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        chicken2n.setText("0");

        chicken3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        chicken3.setText("Curry 2 Chicken");

        chicken3n.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        chicken3n.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        chicken3n.setText("0");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Egg");

        egg1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        egg1.setText("Boilded Egg");

        egg1n.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        egg1n.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        egg1n.setText("0");

        egg2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        egg2.setText("BullsEye Egg");

        egg2n.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        egg2n.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        egg2n.setText("0");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("For Menu of the Date");

        buttonGroup1.add(f1);
        f1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        buttonGroup1.add(f2);
        f2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        buttonGroup1.add(f3);
        f3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        buttonGroup2.add(c1);
        c1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        buttonGroup2.add(c2);
        c2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        buttonGroup2.add(c3);
        c3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3ActionPerformed(evt);
            }
        });

        buttonGroup3.add(e1);
        e1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        buttonGroup3.add(e2);
        e2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(0, 152, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 44, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(chicken2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chicken1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chicken3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(egg1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(egg2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fish3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fish2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fish1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(chicken1n, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(chicken1p, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(fish2n, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(fish2p, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(fish1n, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(fish1p, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(fish3n, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(fish3p, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(chicken2n, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(chicken2p, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(egg1n, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chicken3n, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(chicken3p, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                                    .addComponent(egg1p, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(egg2n, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(egg2p, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(f1)
                            .addComponent(f2)
                            .addComponent(f3)
                            .addComponent(c1)
                            .addComponent(c2)
                            .addComponent(c3)
                            .addComponent(e1)
                            .addComponent(e2))
                        .addGap(50, 50, 50))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fish1)
                        .addComponent(fish1n))
                    .addComponent(fish1p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f1))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fish2p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fish2)
                        .addComponent(fish2n))
                    .addComponent(f2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fish3)
                        .addComponent(fish3n))
                    .addComponent(fish3p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f3))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chicken1)
                        .addComponent(chicken1n))
                    .addComponent(chicken1p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chicken2)
                        .addComponent(chicken2n))
                    .addComponent(chicken2p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chicken3p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chicken3)
                        .addComponent(chicken3n))
                    .addComponent(c3))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(egg1)
                        .addComponent(egg1n))
                    .addComponent(egg1p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(e1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(egg2)
                            .addComponent(egg2n))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(egg2p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(e2))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jToolBar2.add(jPanel1);

        jTabbedPane2.addTab("Meats", jToolBar2);

        jToolBar1.setRollover(true);

        curry11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        curry11.setText("Curry set 01 Option 01");

        curry12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        curry12.setText("Curry set 01 Option 02");

        curry13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        curry13.setText("Curry set 01 Option 03");

        curry11n.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        curry11n.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        curry11n.setText("0");

        curry12n.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        curry12n.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        curry12n.setText("0");

        curry13n.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        curry13n.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        curry13n.setText("0");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("For Menu of the Date");

        buttonGroup4.add(c11);
        c11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        buttonGroup4.add(c12);
        c12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        c12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c12ActionPerformed(evt);
            }
        });

        buttonGroup4.add(c13);
        c13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(curry12, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(curry13, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(curry11, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addGap(74, 74, 74)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(curry11n, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(curry12n, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(curry13n, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(curry11p, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                    .addComponent(curry12p, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(curry13p, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c12)
                    .addComponent(c11)
                    .addComponent(c13))
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(curry11)
                        .addComponent(curry11n))
                    .addComponent(curry11p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c11))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(curry12)
                        .addComponent(curry12n))
                    .addComponent(curry12p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c12))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(curry13)
                        .addComponent(curry13n))
                    .addComponent(curry13p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c13))
                .addContainerGap(223, Short.MAX_VALUE))
        );

        jToolBar1.add(jPanel2);

        jTabbedPane2.addTab("Curry set 01", jToolBar1);

        jToolBar3.setRollover(true);

        curry21.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        curry21.setText("Curry set 02 Option 01");

        curry22.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        curry22.setText("Curry set 02 Option 02");

        curry23.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        curry23.setText("Curry set 02 Option 03");

        curry21n.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        curry21n.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        curry21n.setText("0");

        curry22n.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        curry22n.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        curry22n.setText("0");

        curry23n.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        curry23n.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        curry23n.setText("0");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("For Menu of the Date");

        buttonGroup5.add(c21);
        c21.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        buttonGroup5.add(c22);
        c22.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        buttonGroup5.add(c23);
        c23.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(curry22, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(curry23, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(curry21, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addGap(74, 74, 74)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(curry21n, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(curry22n, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(curry23n, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(curry21p, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                    .addComponent(curry22p, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(curry23p, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c21)
                    .addComponent(c22)
                    .addComponent(c23))
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(curry21)
                        .addComponent(curry21n))
                    .addComponent(curry21p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c21))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(curry22)
                        .addComponent(curry22n))
                    .addComponent(curry22p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c22))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(curry23)
                        .addComponent(curry23n))
                    .addComponent(curry23p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c23))
                .addContainerGap(223, Short.MAX_VALUE))
        );

        jToolBar3.add(jPanel3);

        jTabbedPane2.addTab("Curry set 02", jToolBar3);

        jToolBar4.setRollover(true);

        curry31.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        curry31.setText("Curry set 03 Option 01");

        curry32.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        curry32.setText("Curry set 03 Option 02");

        curry33.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        curry33.setText("Curry set 03 Option 03");

        curry31n.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        curry31n.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        curry31n.setText("0");

        curry32n.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        curry32n.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        curry32n.setText("0");

        curry33n.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        curry33n.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        curry33n.setText("0");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("For Menu of the Date");

        buttonGroup6.add(c31);
        c31.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        buttonGroup6.add(c32);
        c32.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        buttonGroup6.add(c33);
        c33.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(curry32, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(curry33, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(curry31, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addGap(74, 74, 74)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(curry31n, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(curry32n, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(curry33n, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(curry31p, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                    .addComponent(curry32p, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(curry33p, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c31, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(c32, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(c33, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(50, 50, 50))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(curry31)
                        .addComponent(curry31n))
                    .addComponent(curry31p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c31))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(curry32)
                                .addComponent(curry32n))
                            .addComponent(c32))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(curry33)
                                .addComponent(curry33n))
                            .addComponent(curry33p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c33)))
                    .addComponent(curry32p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(215, Short.MAX_VALUE))
        );

        jToolBar4.add(jPanel4);

        jTabbedPane2.addTab("Curry set 03", jToolBar4);

        jToolBar5.setRollover(true);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("<html>\n<body>\nVegetarian Cuisine special prepare for Vegetarians,<br>\nYou can freely edit a Curry for this.\n</body>\n</html>");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setText("Option : ");

        vegtxt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(vegtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(290, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(vegtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(226, Short.MAX_VALUE))
        );

        jToolBar5.add(jPanel5);

        jTabbedPane2.addTab("Special", jToolBar5);

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton1.setText("Log Out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton2.setText("Orders");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton3.setText("Meal Processing");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton4.setText("Main Menu");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Vote Counting Menu");

        vcmdate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        vcmdate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        vcmdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vcmdateActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton5.setText("SetMenu");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Enter a Date (format: 20201201)");

        jButton6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton6.setText("Search");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        warring.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        warring.setForeground(new java.awt.Color(255, 0, 0));
        warring.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(191, 191, 191))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(warring, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vcmdate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vcmdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(warring))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new Order01().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new MealProcessing01().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Loginpage01().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new AdminMainMenu(canteen).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void vcmdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vcmdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vcmdateActionPerformed

    private void c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c3ActionPerformed

    private void c12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c12ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        setMenu();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int tmp1;
        loadVaribles();
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VotingCount01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VotingCount01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VotingCount01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VotingCount01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VotingCount01().setVisible(true);
            }
        });
    }
    
    // load values form datebase to varibles 
    private void loadVaribles(){
        int[] tmp = new int[2];
        Calculations d1 = new Calculations(vcmdate.getText());
        tmp = d1.checkDate();
        if(tmp[0]==1){ 
            warring.setText("* valid Date *");
            menuDate = vcmdate.getText();
            SQLClass s1 = new SQLClass();
            /* get voting count and curry names from database */
            count = s1.getVotingCount(menuDate,canteen);
            cnames = s1.getCurryNames(menuDate,canteen);
            
            calculate();
        }
        else{ 
            if(tmp[0]==0){
                if(tmp[1]==0){
                    warring.setText("* Invalid Date *");
                }
                else{
                    if(tmp[1]==1){
                       warring.setText("* Invalid Date - Incorrect Date *"); 
                    }
                    else{
                        if(tmp[1]==2){
                            warring.setText("* Invalid Date - Incorrect Month *");
                        }
                        else{
                            if(tmp[1]==3){
                                warring.setText("* Invalid Date - Incorrect Year *");
                            }
                        }
                    }
                }
            }
            else{
                if(tmp[0]==3){
                    warring.setText("* Enter a Date *");
                }
            }
        }
        clear();
    }
    
    // calculate the percentage vales for each Curry 
    private void calculate(){
        double[] tot=new double[6];
        
        for(i=0;i<6;++i){tot[i]=0;}
        for(i=0;i<6;++i){
            for(j=0;j<3;++j){
                tot[i]=tot[i]+count[i][j];
            }
        }
        for(i=0;i<6;++i){
            for(j=0;j<3;++j){
                value[i][j]=(count[i][j]/tot[i])*100;
            }
        }
        
        setValues();
    }
    
    // initialisationing values for interface lables 
    private void setValues(){
        String[][] tmp1 = new String[6][3];
        for(i=0;i<6;++i){
            for(j=0;j<3;++j){
                tmp1[i][j] = String.valueOf(count[i][j]);
            }
        }
        
        int[][] tmp = new int[6][3];
        for(i=0;i<6;++i){
            for(j=0;j<3;++j){
                tmp[i][j] = (int)value[i][j];
            }
        }
        
        
        curry11.setText(cnames[0][0]);
        curry12.setText(cnames[0][1]);
        curry13.setText(cnames[0][2]);
        
        curry21.setText(cnames[1][0]);
        curry22.setText(cnames[1][1]);
        curry23.setText(cnames[1][2]);
        
        curry31.setText(cnames[2][0]);
        curry32.setText(cnames[2][1]);
        curry33.setText(cnames[2][2]);
        
        fish1p.setValue(tmp[0][0]);
        fish2p.setValue(tmp[0][1]);
        fish3p.setValue(tmp[0][2]);
        
        chicken1p.setValue(tmp[1][0]);
        chicken2p.setValue(tmp[1][1]);
        chicken3p.setValue(tmp[1][2]);
        
        egg1p.setValue(tmp[2][0]);
        egg2p.setValue(tmp[2][1]);
        
        curry11p.setValue(tmp[3][0]);
        curry12p.setValue(tmp[3][1]);
        curry13p.setValue(tmp[3][2]);
        
        curry21p.setValue(tmp[4][0]);
        curry22p.setValue(tmp[4][1]);
        curry23p.setValue(tmp[4][2]);
        
        curry31p.setValue(tmp[5][0]);
        curry32p.setValue(tmp[5][1]);
        curry33p.setValue(tmp[5][2]);
        
        fish1n.setText(tmp1[0][0]);
        fish2n.setText(tmp1[0][1]);
        fish3n.setText(tmp1[0][2]);
        
        chicken1n.setText(tmp1[1][0]);
        chicken2n.setText(tmp1[1][1]);
        chicken3n.setText(tmp1[1][2]);
        
        egg1n.setText(tmp1[2][0]);
        egg2n.setText(tmp1[2][1]);
        
        curry11n.setText(tmp1[3][0]);
        curry12n.setText(tmp1[3][1]);
        curry13n.setText(tmp1[3][2]);
        
        curry21n.setText(tmp1[4][0]);
        curry22n.setText(tmp1[4][1]);
        curry23n.setText(tmp1[4][2]);
        
        curry31n.setText(tmp1[5][0]);
        curry32n.setText(tmp1[5][1]);
        curry33n.setText(tmp1[5][2]);
    }
    
    private void setMenu(){
        int tmp=0;
        
        for(i=0;i<6;++i){
            menu[i]=0;
        }
        
        if(f1.isSelected()==true){
            menu[0]=1;
        }
        if(f2.isSelected()==true){
            menu[0]=2;
        }
        if(f3.isSelected()==true){
            menu[0]=3;
        }
        
        if(c1.isSelected()==true){
            menu[1]=1;
        }
        if(c2.isSelected()==true){
            menu[1]=2;
        }
        if(c3.isSelected()==true){
            menu[1]=3;
        }
        
        if(e1.isSelected()==true){
            menu[2]=1;
        }
        if(e2.isSelected()==true){
            menu[2]=2;
        }
        
        if(c11.isSelected()==true){
            menu[3]=1;
        }
        if(c12.isSelected()==true){
            menu[3]=2;
        }
        if(c13.isSelected()==true){
            menu[3]=3;
        }
        
        if(c21.isSelected()==true){
            menu[4]=1;
        }
        if(c22.isSelected()==true){
            menu[4]=2;
        }
        if(c23.isSelected()==true){
            menu[4]=3;
        }
        
        if(c31.isSelected()==true){
            menu[5]=1;
        }
        if(c32.isSelected()==true){
            menu[5]=2;
        }
        if(c33.isSelected()==true){
            menu[5]=3;
        }
        
        for(i=0;i<6;++i){
            if(menu[i]==0){
                switch (i){
                    case 0: 
                        warring.setText("Choose a Fish type for menu !!!");
                        tmp=1;
                        break;
                    case 1: 
                        warring.setText("Choose a Chiken type for menu !!!");
                        tmp=1;
                        break;
                    case 2: 
                        warring.setText("Choose a Egg type for menu !!!");
                        tmp=1;
                        break;
                    case 3: 
                        warring.setText("Choose a Curry set 01 option for menu !!!");
                        tmp=1;
                        break;
                    case 4: 
                        warring.setText("Choose a Curry set 02 option for menu !!!");
                        tmp=1;
                        break;
                    case 5: 
                        warring.setText("Choose a Curry set 03 option for menu !!!");
                        tmp=1;
                        break;
                }
            }
        }
        if(tmp==0){
            warring.setText("menu is set");
            /* insert menu data to database
            int t1 = insertMenu(canteen,menuDate,menu);
            if(t1==1){
                new Massage("Menu for date: "+menuDate+" is set ").setVisible(true);
            }
            else{
                new Massage("Something wents wrong !!! Menu for date: "+menuDate+" isn't set ").setVisible(true);
            }
            */
        }
    }
    
    private void clear(){
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        buttonGroup3.clearSelection();
        buttonGroup4.clearSelection();
        buttonGroup5.clearSelection();
        buttonGroup6.clearSelection();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JCheckBox c1;
    private javax.swing.JCheckBox c11;
    private javax.swing.JCheckBox c12;
    private javax.swing.JCheckBox c13;
    private javax.swing.JCheckBox c2;
    private javax.swing.JCheckBox c21;
    private javax.swing.JCheckBox c22;
    private javax.swing.JCheckBox c23;
    private javax.swing.JCheckBox c3;
    private javax.swing.JCheckBox c31;
    private javax.swing.JCheckBox c32;
    private javax.swing.JCheckBox c33;
    private javax.swing.JLabel chicken1;
    private javax.swing.JLabel chicken1n;
    private javax.swing.JProgressBar chicken1p;
    private javax.swing.JLabel chicken2;
    private javax.swing.JLabel chicken2n;
    private javax.swing.JProgressBar chicken2p;
    private javax.swing.JLabel chicken3;
    private javax.swing.JLabel chicken3n;
    private javax.swing.JProgressBar chicken3p;
    private javax.swing.JLabel curry11;
    private javax.swing.JLabel curry11n;
    private javax.swing.JProgressBar curry11p;
    private javax.swing.JLabel curry12;
    private javax.swing.JLabel curry12n;
    private javax.swing.JProgressBar curry12p;
    private javax.swing.JLabel curry13;
    private javax.swing.JLabel curry13n;
    private javax.swing.JProgressBar curry13p;
    private javax.swing.JLabel curry21;
    private javax.swing.JLabel curry21n;
    private javax.swing.JProgressBar curry21p;
    private javax.swing.JLabel curry22;
    private javax.swing.JLabel curry22n;
    private javax.swing.JProgressBar curry22p;
    private javax.swing.JLabel curry23;
    private javax.swing.JLabel curry23n;
    private javax.swing.JProgressBar curry23p;
    private javax.swing.JLabel curry31;
    private javax.swing.JLabel curry31n;
    private javax.swing.JProgressBar curry31p;
    private javax.swing.JLabel curry32;
    private javax.swing.JLabel curry32n;
    private javax.swing.JProgressBar curry32p;
    private javax.swing.JLabel curry33;
    private javax.swing.JLabel curry33n;
    private javax.swing.JProgressBar curry33p;
    private javax.swing.JCheckBox e1;
    private javax.swing.JCheckBox e2;
    private javax.swing.JLabel egg1;
    private javax.swing.JLabel egg1n;
    private javax.swing.JProgressBar egg1p;
    private javax.swing.JLabel egg2;
    private javax.swing.JLabel egg2n;
    private javax.swing.JProgressBar egg2p;
    private javax.swing.JCheckBox f1;
    private javax.swing.JCheckBox f2;
    private javax.swing.JCheckBox f3;
    private javax.swing.JLabel fish1;
    private javax.swing.JLabel fish1n;
    private javax.swing.JProgressBar fish1p;
    private javax.swing.JLabel fish2;
    private javax.swing.JLabel fish2n;
    private javax.swing.JProgressBar fish2p;
    private javax.swing.JLabel fish3;
    private javax.swing.JLabel fish3n;
    private javax.swing.JProgressBar fish3p;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JToolBar jToolBar4;
    private javax.swing.JToolBar jToolBar5;
    private javax.swing.JTextField vcmdate;
    private javax.swing.JTextField vegtxt;
    private javax.swing.JLabel warring;
    // End of variables declaration//GEN-END:variables
}
